brand_list = [
    "ford",
    "porsche",
    "bmw",
    "jaguar",
    "vauxhall",
    "volkswagen",
    "honda",
    "ferrari",
    "nissan",
    "toyota",
    "land rover",
    "volvo",
    "lamborghini",
    "mercedes-benz",
    "renault",
    "aston martin",
    "fiat",
    "citroen",
    "rolls-royce",
    "peugeot",
    "audi",
    "bentley",
    "mazda",
    "hyundai",
    "kia",
    "mitsubishi",
    "skoda",
    "suzuki",
    "seat",
    "mini",
    "alfa romeo",
    "chevrolet",
    "jeep",
    "lexus",
    "subaru",
    "tesla",
    "maserati",
    "mg",
    "cadillac",
    "bugatti",
    "general motors",
    "dacia",
    "lotus",
    "hummer",
    "smart",
    "isuzu",
    "dodge",
    "infiniti",
    "abarth",
    "koenigsegg"]